services:
  web-test:
    image: nginx:alpine
    container_name: app-profesor
    networks:
      - plataforma_red-proxy # Importante: debe coincidir con el nombre de tu red real

networks:
  plataforma_red-proxy:
    external: true

# ##  3. Gesti贸n de Usuarios y Permisos (Requisito 2 y 7)
#
# Se ha implementado una capa de automatizaci贸n para la gesti贸n de usuarios de despliegue,
# cumpliendo con las pol铆ticas de seguridad del sistema operativo.
#
# - Script de Automatizaci贸n:
#   El script `crear_usuario_deploy.sh` automatiza la creaci贸n del usuario,
#   la asignaci贸n al grupo `docker` y la preparaci贸n del entorno de trabajo.
#
# - Estructura de Trabajo:
#   Cada usuario dispone de un directorio `~/apps/` aislado, donde gestiona
#   sus propios proyectos mediante Docker Compose, garantizando que el entorno
#   del sistema permanezca limpio y organizado.
#
# ### Desplegar la App del Profesor
#
# La aplicaci贸n se gestiona de forma aislada dentro del entorno del usuario de despliegue.
#
# 1. Ubicaci贸n real:
#    /home/deploy-profesor/apps/
#
# 2. Procedimiento:
#    - Acceder como usuario `deploy-profesor`.
#    - Clonar o copiar el proyecto dentro de la carpeta `apps/`.
#    - Levantar el servicio con el comando:
#      docker compose up -d
#
# 3. Interconexi贸n:
#    Gracias a que el contenedor se conecta a la red externa `red-proxy`,
#    el tr谩fico fluye desde Nginx hacia la aplicaci贸n de forma transparente.











